# Generated by Django 4.0.4 on 2022-04-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
